/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.potapova;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void test() {
    ExpressionParser parser = new ExpressionParser();
    Assertions.assertEquals(1.0,parser.parse("- + 2.0 2.0 3.0"));
    Assertions.assertThrows(RuntimeException.class , ()-> parser.parse("/ 1 0"));
  }
}
