/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.apotapova;

import org.junit.Test;
import static org.junit.Assert.*;

public class SubstringsFinderTest {
    @Test public void someLibraryMethodReturnsTrue() {
        SubstringsFinder classUnderTest = new SubstringsFinder();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
