/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.apotapova;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class SubstringsFinderTest {

  @Test
  void testBigText() {
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("src/test/resources/BigText.txt"));
    } catch (FileNotFoundException e) {
      throw new RuntimeException(e);
    }
    SubstringsFinder finder = new SubstringsFinder(reader);
    Assertions.assertEquals(10, finder.findSubstring("The Boy Who Lived"));
  }
  @Test
  void testBigText2() {
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("src/test/resources/BigText.txt"));
    } catch (FileNotFoundException e) {
      throw new RuntimeException(e);
    }
    SubstringsFinder finder = new SubstringsFinder(reader);
    Assertions.assertNull(finder.findSubstring("This line is not in the text"));
  }

  @Test
  void testBufferOverlap() {
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("src/test/resources/BufferOverlap.txt"));
    } catch (FileNotFoundException e) {
      throw new RuntimeException(e);
    }
    SubstringsFinder finder = new SubstringsFinder(reader);
    Assertions.assertEquals(26, finder.findSubstring("---->.<----"));
  }
  @Test
  void testUTF8() {
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("src/test/resources/UTF8.txt"));
    } catch (FileNotFoundException e) {
      throw new RuntimeException(e);
    }
    SubstringsFinder finder = new SubstringsFinder(reader);
    Assertions.assertEquals(11683, finder.findSubstring("©"));
  }
  @Test
  void testAAAinAAAAAAAA() {
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("src/test/resources/AAAinAAAAAAAA.txt"));
    } catch (FileNotFoundException e) {
      throw new RuntimeException(e);
    }
    SubstringsFinder finder = new SubstringsFinder(reader);
    Assertions.assertEquals(0, finder.findSubstring("AAA"));
  }
}
