/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.apotapova;

import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import org.junit.jupiter.api.Test;
import ru.nsu.fit.apotapova.Graphs.AdjacencyListsGraph;
import ru.nsu.fit.apotapova.Graphs.Graph;

class MdjacencyMatrixGraphTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}