/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.apotapova;

public class SubstringsFinder {
    public boolean someLibraryMethod() {
        return true;
    }
}
